version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/client/Microsoft.Identity.Client.Broker
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/client/Microsoft.Identity.Client.Desktop
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/client/Microsoft.Identity.Client
    schedule:
      interval: daily
