name: Bug Report
description: Broken or unintended behavior with one of our libraries.
title: '[Bug] '
labels: [bug-unconfirmed, question]
body:
- type: markdown
  attributes:
    value: |
      ## Before Submitting your Issue
      Please make sure that your question or issue is not already covered in [MSAL docs](https://learn.microsoft.com/en-us/entra/msal/dotnet/) or [samples](https://learn.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code?tabs=apptype).

      **Logs and network traces**
      Without logs or traces, it is unlikely that the team can investigate your issue. Capturing logs and network traces is described in [Logging wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/logging).

- type: markdown
  attributes:
    value: |
      ## Issue Details   
    
- type: input
  attributes:
    label: Library Version used
    description: "Please enter the latest version this issue can be reproduced in."
    placeholder: "4.54.0"
  validations:
    required: true
    
- type: textarea
  attributes:
    label: .Net Framework
    description: "Please enter the .NET Framework version your application was developed in."
  validations:
    required: true

- type: dropdown
  attributes:
    label: Public, Confidential or Managed Identity Client?
    description: "Are you using PublicClientApplication,  ConfidentialClientApplication or ManagedIdentityApplication?"
    multiple: true
    options: 
      - "Public"
      - "Confidential"
      - "Managed Identity"
  validations:
    required: true

- type: dropdown
  attributes:
    label: Application Type?
    description: "Please select your application type"
    multiple: true
    options: 
      - "Desktop"
      - "Mobile"
      - "Web App"
      - "Web API"
      - "Daemon App" 
  validations:
    required: true   

- type: dropdown
  attributes:
    label: Authentication Flow?
    description: "What authentication flow has the issue?"
    multiple: true
    options: 
      - "Interactive (broker)"
      - "Interactive (embedded or system browser)"
      - "Integrated Windows Authentication"
      - "Username / Password"
      - "Device code (browserless)"
      - "Authorization code"
      - "On-Behalf-Of"
      - "Client credentials (service-to-service calls)"
      - "Long Running OBO"
      - "Managed Identity"
      - "Other"
  validations:
    required: true    

- type: dropdown
  attributes:
    label: Is this a new or existing app?
    description: "Is this a new or existing app?"
    multiple: true
    options: 
      - "The app is in production, and I have upgraded to a new version of MSAL"
      - "The app is in production, I haven't upgraded MSAL, but started seeing this issue"
      - "This is a new app or experiment"
  validations:
    required: true        

- type: textarea
  attributes:
    label: Issue Description and Reproduction Steps
    description: "Briefly explain the issue you are seeing. Please also provide steps to reproduce or a link to a sample which demonstrates this behavior."
    
- type: textarea
  attributes:
    label: Error Message
    description: "Please provide any error message you are receiving and a stack trace."

- type: textarea
  attributes:
    label: Msal Logs
    description: "Please provide verbose level log messages from msal. [Learn more](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-logging-dotnet)"
       
- type: textarea
  attributes:
    label: Relevant Code Snippets
    description: "Please provide relevant code snippets that can be used to reproduce this issue."
    render: javascript
  validations:
    required: false
       
- type: textarea
  attributes:
    label: Expected Behavior
    description: "Please describe what you expect the behavior to be."
  validations:
    required: true
    
- type: dropdown
  attributes:
    label: Identity Provider
    options: 
      - Azure AD / MSA
      - Azure B2C Basic Policy
      - Azure B2C Custom Policy
      - ADFS
      - CIAM
      - Other
  validations:
    required: true
       
- type: input
  attributes:
    label: Regression
    description: "If this behavior worked before, please enter the last working version(s)."
    placeholder: "MSAL version : "

- type: textarea
  attributes:
    label: Solution
    description: "Possible solution if you know of any."
  validations:
    required: false
    
- type: dropdown
  attributes:
    label: Source
    description: "Are you an internal or external customer?"
    options: 
      - External (Customer)
      - Internal (Microsoft)
      
  validations: 
     required: false
    
- type: markdown
  attributes:
    value: "## Security Reporting"
- type: markdown
  attributes:
    value: |
      If you find a security issue with our libraries or services [please report it to the Microsoft Security Response Center (MSRC)](https://aka.ms/report-security-issue) with as much detail as possible. Your submission may be eligible for a bounty through the [Microsoft Bounty](http://aka.ms/bugbounty) program. Please do not post security issues to GitHub Issues or any other public site. We will contact you shortly upon receiving the information. We encourage you to get notifications of when security incidents occur by visiting [this page](https://www.microsoft.com/msrc/technical-security-notifications) and subscribing to Security Advisory Alerts.
