name: Run performance benchmarks
on:
  push:
    branches:
      - main
      - pmaytak/perf-benchmark-action
    paths:
      - src/client/Microsoft.Identity.Client/*

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run performance benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.101'
      - name: Run benchmark
        run: cd tests/Microsoft.Identity.Test.Performance && dotnet run -c release --exporters json 

      - name: Download previous benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: BenchmarkDotNet Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: tests/Microsoft.Identity.Test.Performance/BenchmarkDotNet.Artifacts/results/*-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # auto-push: true
          external-data-json-path: ./cache/benchmark-data.json
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '10%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@pmaytak'
          summary-always: true
